using ArkansasServe.Functions.Models;

namespace ArkansasServe.Functions.Services;

/// <summary>
/// Turns a <see cref="RecurrenceRule"/> into the UTC start instants of every occurrence.
///
/// Pure and static: no Cosmos, no clock, no config. Given the same seed and rule it returns
/// the same list, which is what makes the DST behaviour below testable at all.
///
/// ── Why this walks the LOCAL calendar ──────────────────────────────────────────────
/// Adding 7×24h to a UTC instant is NOT "the same time next week". A 1pm CST event stored
/// as 19:00Z keeps rendering as 1pm until DST begins, after which 19:00Z is 2pm CDT — so a
/// naive series silently drifts by an hour, twice a year, for every occurrence after the
/// transition. Registrations, shifts and check-in all inherit the wrong time.
///
/// So occurrences are generated by stepping the local calendar with the wall-clock time held
/// fixed, then converting each result back to UTC. "Every Tuesday at 1pm" stays 1pm.
/// </summary>
public static class RecurrenceExpander
{
	/// <summary>
	/// Hard ceiling on a single series. Occurrences are real documents, so a typo in the end
	/// date ("until 2099") would otherwise mint tens of thousands of them.
	/// </summary>
	public const int MaxOccurrences = 100;

	/// <summary>
	/// Arkansas Serve is a single-state programme and Arkansas is entirely US Central, so the
	/// zone is a constant rather than a field on the org. This is the one place that
	/// assumption lives: give Event or Tenant a timezone and only this needs to change.
	///
	/// The IANA id works on both the Linux Function App and Windows dev boxes — .NET 6+ uses
	/// ICU on Windows too, so "America/Chicago" resolves on both. The Windows id
	/// ("Central Standard Time") would NOT resolve on Linux.
	/// </summary>
	private static readonly TimeZoneInfo Zone = TimeZoneInfo.FindSystemTimeZoneById("America/Chicago");

	/// <summary>
	/// Expands <paramref name="rule"/> from <paramref name="seedUtc"/>.
	/// The seed is always the first occurrence. Returns an error message instead of throwing
	/// when the rule itself is unusable, so callers can hand it straight to the client.
	/// </summary>
	public static (List<DateTime>? Starts, string? Error) Expand(DateTime seedUtc, RecurrenceRule rule)
	{
		if (rule == null) return (null, "A recurrence rule is required");

		var freq = (rule.Frequency ?? string.Empty).Trim().ToLowerInvariant();
		if (freq is not ("daily" or "weekly" or "monthly"))
			return (null, "Recurrence frequency must be daily, weekly or monthly");

		var hasUntil = rule.Until.HasValue;
		var hasCount = rule.Count.HasValue;
		if (hasUntil == hasCount)
			return (null, "Give the series either an end date or a number of occurrences, not both and not neither");
		if (hasCount && (rule.Count!.Value < 1 || rule.Count.Value > MaxOccurrences))
			return (null, $"A series must repeat between 1 and {MaxOccurrences} times");

		// Everything below is computed on the local calendar.
		var seedLocal = TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(seedUtc, DateTimeKind.Utc), Zone);
		var timeOfDay = seedLocal.TimeOfDay;
		var seedDate = seedLocal.Date;

		// Until is compared as a local calendar DAY, inclusive. Converting the instant first
		// is what stops a 7pm end date from reading as the next day and adding an occurrence.
		DateTime? untilDate = null;
		if (hasUntil)
		{
			untilDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(rule.Until!.Value, DateTimeKind.Utc), Zone).Date;
			if (untilDate < seedDate)
				return (null, "The series end date is before its start");
		}

		var (dates, ruleError) = freq switch
		{
			"daily" => (EnumerateDaily(seedDate), null),
			"weekly" => EnumerateWeekly(seedDate, rule),
			"monthly" => (EnumerateMonthly(seedDate, rule.ByNthWeekday), null),
			_ => (null, "Unsupported frequency"),
		};
		if (ruleError != null) return (null, ruleError);

		var starts = new List<DateTime>();
		var skippedInvalidLocalTimes = 0;
		foreach (var date in dates!)
		{
			if (untilDate.HasValue && date > untilDate.Value) break;
			if (hasCount && starts.Count >= rule.Count!.Value) break;
			if (starts.Count >= MaxOccurrences) break;

			var local = date + timeOfDay;

			// Spring-forward: 2:00–2:59am simply does not exist on that date, and converting
			// it throws. Skip rather than invent a time nobody chose — it can only bite a
			// series whose start time sits inside the lost hour.
			if (Zone.IsInvalidTime(local)) { skippedInvalidLocalTimes++; continue; }

			// Fall-back: 1:00–1:59am happens twice. ConvertTimeToUtc resolves an ambiguous
			// local time to the STANDARD offset, i.e. the second (later) instant. Either is
			// defensible; the important part is that it is deterministic and does not throw.
			starts.Add(TimeZoneInfo.ConvertTimeToUtc(DateTime.SpecifyKind(local, DateTimeKind.Unspecified), Zone));
		}

		if (starts.Count == 0)
			return (null, "That pattern produces no dates");
		if (hasCount && starts.Count < rule.Count!.Value && skippedInvalidLocalTimes == 0)
			return (null, "That pattern runs out of dates before reaching the requested number of occurrences");

		return (starts, null);
	}

	private static IEnumerable<DateTime> EnumerateDaily(DateTime seedDate)
	{
		for (var d = seedDate; ; d = d.AddDays(1)) yield return d;
	}

	private static (IEnumerable<DateTime>?, string?) EnumerateWeekly(DateTime seedDate, RecurrenceRule rule)
	{
		var seedDow = (int)seedDate.DayOfWeek;
		var days = (rule.DaysOfWeek is { Count: > 0 })
			? rule.DaysOfWeek.Distinct().OrderBy(d => d).ToList()
			: [seedDow];

		if (days.Any(d => d is < 0 or > 6))
			return (null, "Days of the week must be 0 (Sunday) through 6 (Saturday)");
		// The start must be one of its own occurrences; otherwise the series would begin on a
		// date its own pattern excludes.
		if (!days.Contains(seedDow))
			return (null, "The start date must fall on one of the selected days of the week");

		return (Walk(), null);

		IEnumerable<DateTime> Walk()
		{
			for (var d = seedDate; ; d = d.AddDays(1))
				if (days.Contains((int)d.DayOfWeek)) yield return d;
		}
	}

	private static IEnumerable<DateTime> EnumerateMonthly(DateTime seedDate, bool byNthWeekday)
	{
		if (byNthWeekday)
		{
			// "the 3rd Saturday", derived from the seed so it cannot contradict it.
			var dow = seedDate.DayOfWeek;
			var nth = (seedDate.Day - 1) / 7 + 1;
			for (var month = new DateTime(seedDate.Year, seedDate.Month, 1); ; month = month.AddMonths(1))
			{
				var d = NthWeekdayOf(month.Year, month.Month, dow, nth);
				// A 5th Saturday does not exist every month. Skip it — the alternative,
				// sliding to the 4th or into the next month, invents a date nobody picked.
				if (d.HasValue && d.Value >= seedDate) yield return d.Value;
			}
		}
		else
		{
			// "on the 17th". Months without that day (the 31st of February) are skipped, per
			// RFC 5545. Clamping to the 28th would silently move the event.
			var day = seedDate.Day;
			for (var month = new DateTime(seedDate.Year, seedDate.Month, 1); ; month = month.AddMonths(1))
			{
				if (day > DateTime.DaysInMonth(month.Year, month.Month)) continue;
				var d = new DateTime(month.Year, month.Month, day);
				if (d >= seedDate) yield return d;
			}
		}
	}

	private static DateTime? NthWeekdayOf(int year, int month, DayOfWeek dow, int nth)
	{
		var first = new DateTime(year, month, 1);
		var offset = ((int)dow - (int)first.DayOfWeek + 7) % 7;
		var day = 1 + offset + (nth - 1) * 7;
		return day <= DateTime.DaysInMonth(year, month) ? new DateTime(year, month, day) : null;
	}
}
